version: "3.7"

services:
  app:
    build: .
    volumes:
        - /C/xampp/htdocs/prjs/node/docker:/usr/src
        - /usr/src/node_modules
    environment:
        MONGO_URL: "mongodb://db:27017/test"
    depends_on:
        - db
    ports:
        - "3000-3010:3000"

  db:
    image: mongo
